version: '2'
services:
  ros-master:
    image: gramaziokohler/ros-noetic-moveit:latest
    container_name: ros-master
    ports:
      - "11311:11311"
    command:
      - roscore

  ros-bridge:
    image: gramaziokohler/ros-noetic-dfab:22.12
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "9090:9090"
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch
      
  abb-driver-1:
    image: gramaziokohler/ros-noetic-dfab:22.12
    container_name: abb-driver-1
    environment:
      - ROS_HOSTNAME=abb-driver-1
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - compas_rrc_driver
      - bringup.launch
      - robot_ip:=192.168.20.1
      - robot_streaming_port:=30101
      - robot_state_port:=30201
      - namespace:=rob1

  abb-driver-2:
    image: gramaziokohler/ros-noetic-dfab:22.12
    container_name: abb-driver-2
    environment:
      - ROS_HOSTNAME=abb-driver-2
      - ROS_MASTER_URI=http://ros-master:11311
    depends_on:
      - ros-master
    command:
      - roslaunch
      - --wait
      - compas_rrc_driver
      - bringup.launch
      - robot_ip:=192.168.10.5
      - robot_streaming_port:=30101
      - robot_state_port:=30201
      - namespace:=rob2
